name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Railpack
        run: curl -sSL https://railpack.com/install.sh | sh

      - name: Railpack prepare
        run: railpack prepare . --plan-out railpack-plan.json --info-out railpack-info.json

      - name: Railpack build
        run: |
          docker buildx build \
            --build-arg BUILDKIT_SYNTAX="ghcr.io/railwayapp/railpack-frontend" \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            -f railpack-plan.json \
            .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
