name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-platforms:
    runs-on: ubuntu-latest
    environment: build
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Railpack
        run: curl -sSL https://railpack.com/install.sh | sh

      - name: Railpack prepare
        run: railpack prepare . --plan-out railpack-plan.json --info-out railpack-info.json

      - name: Railpack build
        run: |
          PLATFORM_TAG=$(echo ${{ matrix.platform }} | sed 's/\//_/g')
          docker buildx build \
            --build-arg BUILDKIT_SYNTAX="ghcr.io/railwayapp/railpack-frontend" \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-$PLATFORM_TAG \
            -f railpack-plan.json \
            --platform ${{ matrix.platform }} \
            --push \
            .

      - name: Verify image push
        run: |
          PLATFORM_TAG=$(echo ${{ matrix.platform }} | sed 's/\//_/g')
          for i in {1..10}; do
            if docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-$PLATFORM_TAG; then
              echo "Image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-$PLATFORM_TAG is available"
              exit 0
            fi
            echo "Waiting for image to be available... Attempt $i"
            sleep 10
          done
          echo "Error: Failed to verify image push for ${{ matrix.platform }}"
          exit 1

  create-manifest:
    needs: build-platforms
    runs-on: ubuntu-latest
    environment: build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify images before manifest creation
        run: |
          for platform in linux_amd64 linux_arm64; do
            if ! docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-$platform; then
              echo "Error: Image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-$platform is not available"
              exit 1
            fi
            echo "Verified ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-$platform is available"
          done

      - name: Create and push manifest
        run: |
          # Check if manifest exists and remove it if it does
          if docker manifest inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest >/dev/null 2>&1; then
            docker manifest rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          fi
          
          # Create new manifest
          docker manifest create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-linux_amd64 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-linux_arm64
          
          # Annotate manifests
          docker manifest annotate ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-linux_amd64 \
            --os linux --arch amd64
          docker manifest annotate ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-linux_arm64 \
            --os linux --arch arm64
          
          # Push manifest
          docker manifest push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
